version: '2'
services:
    assoi:
        restart: unless-stopped
        build: ./assoi
        expose:
            - "4129"
        links:
            - assoi-redis:redis
            - assoi-postgres:postgres
            - assoi-mongo:mongo
            - assoi-rabbit:rabbit
        volumes:
            - ./ugmk:/www
        working_dir: /www
        command: npm start
    assoi-redis:
        image: redis:latest
        restart: unless-stopped
    assoi-postgres:
        image: postgres:latest
        restart: unless-stopped
        environment:
            - PGDATA=/var/lib/postgresql/data/vol
        volumes:
            - ./postgres/data:/var/lib/postgresql/data/vol
            - ./postgres/assoi.dump:/var/lib/postgresql/assoi.dump:ro
            - ./postgres/import.sh:/var/lib/postgresql/import.sh:ro
    assoi-mongo:
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - ./mongo/data:/data/db
    assoi-rabbit:
        image: rabbitmq:3-management
        restart: unless-stopped
        environment:
           - RABBITMQ_DEFAULT_USER=jet
           - RABBITMQ_DEFAULT_PASS=jetparole12j
    assoi-nginx:
        image: nginx:stable
        restart: unless-stopped
        links:
            - assoi
        ports:
            - "8080:80"
        volumes:
            # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./ugmk:/www:ro
        command: /bin/bash -c "nginx -g 'daemon off;'"
